version: "3.8"

services: 

    frontend:
        build: ./frontend
        ports:
            - 3000:3000      

    frontend-tests:
        image: movieo_frontend
        command: npm test

    backend:
        build: ./backend
        ports:
            - 3001:3001
        environment: 
            DB_URL: mongodb://database/movieo
        command: ./docker-entrypoint.sh
        
    backend-tests:
        image: movieo_backend
        environment: 
            DB_URL: mongodb://database/movieo
        command:  npm test
            
    database:
        image: mongo:4.0-xenial
        ports: 
            - 27017:27017
        volumes: 
            - movieo:/data/db

volumes:
    movieo:
